# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 22:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalPipeline',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'approval pipelines',
                'verbose_name': 'approval pipeline',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ApprovalStep',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('can_delete', models.BooleanField(default=False, help_text='Whether or not owned objects can be deleted', verbose_name='can delete owned objects')),
                ('can_edit', models.BooleanField(default=False, help_text='Whether or not owned objects can be edited.  This may be False for most non-edit steps, such as Approval, Published, or automatic Approval steps', verbose_name='can edit owned objects')),
                ('private_to_group', models.BooleanField(default=True, help_text='Whether the object is made private to its group.  This is done for most steps, and should typically only be disabled for a published step.', verbose_name='make owned objects private to group')),
                ('approval_step', models.ForeignKey(blank=True, default=None, help_text='The step that ownership is given to on approval', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailapproval.ApprovalStep', verbose_name='approval step')),
                ('owned_collection', models.ForeignKey(blank=True, default=None, help_text='The collection that collection member objects are assigned to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Collection', verbose_name='owned collection')),
                ('owned_group', models.ForeignKey(blank=True, default=None, help_text='The group that permissions are modified for on entering or leaving this step. This should apply for pages as well as collections.  For all intents and purposes, users in this group are owned by this step, and everything they do is subject to the approval pipeline.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='auth.Group', verbose_name='owned group')),
                ('rejection_step', models.ForeignKey(blank=True, default=None, help_text='The step that ownership is given to on rejection', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailapproval.ApprovalStep', verbose_name='rejection step')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
